name: dio_http_formatter
description: A Dio interceptor for pretty printing the HTTP request/response to be printed in the console for easier debugging
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dio: ^3.0.9
  logger: ^0.9.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
